[api]
token = "YOUR_API_TOKEN"        # optional: can also store in .env
secret = "YOUR_API_SECRET"      # optional: can also store in .env

# Optional: TOTP secret if you use TOTP for login
[api.totp]
secret = ""  # example: "JBSWY3DPEHPK3PXP"
